name: zydex_hr
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  page_transition: ^2.1.0
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  firebase_remote_config: ^5.1.5
  mixpanel_flutter: ^2.3.3
  shared_preferences: ^2.3.3
  permission_handler: ^11.3.1
  get: ^4.6.6
  intl: ^0.19.0
  geolocator: ^13.0.2
  scroll_wheel_date_picker: ^0.0.2+1
  scroll_time_picker: ^1.1.2
  skeletonizer: ^1.4.2
  flutter_svg: ^2.0.14
  dropdown_button2: ^2.3.9
  speech_to_text: ^7.0.0
  avatar_glow: ^3.0.1
  lottie: ^3.1.3
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_advanced_drawer: ^1.3.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/svg_icons/
    - assets/svg_images/
    - assets/animation/AnimationSplash.json
    # - images/a_dot_ham.jpeg

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/nunito.ttf

    - family: NunitoBold
      fonts:
        - asset: fonts/nunitobold.ttf

    - family: NunitoItalic
      fonts:
        - asset: fonts/nunitoitalic.ttf

    - family: NunitoLight
      fonts:
        - asset: fonts/nunitolight.ttf

    - family: NunitoSans
      fonts:
        - asset: fonts/nunitosans.ttf
